// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDihM_1L11nrc3BFRSihfLenkF0b3KN7Mk',
    appId: '1:880416902360:web:9116e22b3778c273aedbad',
    messagingSenderId: '880416902360',
    projectId: 'mini-e-commerce-2dfad',
    authDomain: 'mini-e-commerce-2dfad.firebaseapp.com',
    storageBucket: 'mini-e-commerce-2dfad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-WYusA4tHyCV0HsD8dfVG-spfQMgC05U',
    appId: '1:880416902360:android:5fa54c703953a5d5aedbad',
    messagingSenderId: '880416902360',
    projectId: 'mini-e-commerce-2dfad',
    storageBucket: 'mini-e-commerce-2dfad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcmIVQXBo_gTAhjtwuOL5BWYbppgZz8Oo',
    appId: '1:880416902360:ios:f664856cfed00d49aedbad',
    messagingSenderId: '880416902360',
    projectId: 'mini-e-commerce-2dfad',
    storageBucket: 'mini-e-commerce-2dfad.firebasestorage.app',
    iosBundleId: 'com.libascollective.minicommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcmIVQXBo_gTAhjtwuOL5BWYbppgZz8Oo',
    appId: '1:880416902360:ios:b83db0e16c4844bfaedbad',
    messagingSenderId: '880416902360',
    projectId: 'mini-e-commerce-2dfad',
    storageBucket: 'mini-e-commerce-2dfad.firebasestorage.app',
    iosBundleId: 'com.example. ',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDihM_1L11nrc3BFRSihfLenkF0b3KN7Mk',
    appId: '1:880416902360:web:213387cdda455c61aedbad',
    messagingSenderId: '880416902360',
    projectId: 'mini-e-commerce-2dfad',
    authDomain: 'mini-e-commerce-2dfad.firebaseapp.com',
    storageBucket: 'mini-e-commerce-2dfad.firebasestorage.app',
  );
}
