import 'package:flutter/material.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'products': 'Products',
      'searchProducts': 'Search products...',
      'all': 'All',
      'electronics': 'Electronics',
      'clothing': 'Clothing',
      'books': 'Books',
      'home': 'Home',
      'noProductsFound': 'No products found',
      'retry': 'Retry',
      'cart': 'Cart',
      'profile': 'Profile',
      'addToCart': 'Add to Cart',
      'removeFromCart': 'Remove from Cart',
      'quantity': 'Quantity',
      'total': 'Total',
      'checkout': 'Checkout',
      'proceedToCheckout': 'Proceed to Checkout',
      'paymentSuccessful': 'Payment successful! Order confirmed for',
      'paymentFailed': 'Payment failed',
      'userNotAuthenticated': 'User not authenticated',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'cancel': 'Cancel',
      'save': 'Save',
      'edit': 'Edit',
      'delete': 'Delete',
      'confirm': 'Confirm',
      'clearCart': 'Clear Cart',
      'clearCartConfirmation': 'Are you sure you want to clear your cart?',
      'yes': 'Yes',
      'no': 'No',
      'emptyCart': 'Your cart is empty',
      'cartSummary': 'Cart Summary',
      'subtotal': 'Subtotal',
      'tax': 'Tax',
      'shipping': 'Shipping',
      'totalAmount': 'Total Amount',
      'itemCount': 'Item Count',
      'items': 'Items',
      'processingCheckout': 'Processing checkout...',
      'orderConfirmed': 'Order confirmed',
      'orderFailed': 'Order failed',
      'language': 'Language',
      'english': 'English',
      'arabic': 'Arabic',
      'changeLanguage': 'Change Language',
      'selectLanguage': 'Select Language',
      'currentLanguage': 'Current Language',
      'languageChanged': 'Language changed',
      'languageChangeError': 'Failed to change language',
      'languageChangeSuccess': 'Language changed successfully',
      'languageChangeInfo': 'Changing language...',
      'languageChangeConfirm': 'Are you sure you want to change the language?',
      'languageChangeCancel': 'Cancel language change',
      'languageChangeSave': 'Save language change',
      'languageChangeReset': 'Reset language',
      'languageChangeDefault': 'Default language',
      'languageChangeCustom': 'Custom language',
      'languageChangeSystem': 'System language',
      'languageChangeUser': 'User language',
      'languageChangeApp': 'App language',
      'languageChangeDevice': 'Device language',
      'languageChangeLocale': 'Locale language',
      'languageChangeRegion': 'Region language',
      'languageChangeCountry': 'Country language',
      'languageChangeCurrency': 'Currency language',
      'languageChangeFormat': 'Format language',
      'languageChangeDirection': 'Direction language',
      'languageChangeRTL': 'Right to Left',
      'languageChangeLTR': 'Left to Right',
      'languageChangeAuto': 'Auto',
      'languageChangeManual': 'Manual',
      'languageChangeOn': 'On',
      'languageChangeOff': 'Off',
      'languageChangeEnabled': 'Enabled',
      'languageChangeDisabled': 'Disabled',
      'languageChangeActive': 'Active',
      'languageChangeInactive': 'Inactive',
      'languageChangePrimary': 'Primary',
      'languageChangeSecondary': 'Secondary',
      'languageChangeTertiary': 'Tertiary',
      'languageChangeQuaternary': 'Quaternary',
      'languageChangeQuinary': 'Quinary',
      'languageChangeSenary': 'Senary',
      'languageChangeSeptenary': 'Septenary',
      'languageChangeOctonary': 'Octonary',
      'languageChangeNonary': 'Nonary',
      'languageChangeDenary': 'Denary',
      'map': 'Map',
    },
    'ar': {
      'products': 'المنتجات',
      'searchProducts': 'البحث عن المنتجات...',
      'all': 'الكل',
      'electronics': 'الإلكترونيات',
      'clothing': 'الملابس',
      'books': 'الكتب',
      'home': 'المنزل',
      'noProductsFound': 'لم يتم العثور على منتجات',
      'retry': 'إعادة المحاولة',
      'cart': 'عربة التسوق',
      'profile': 'الملف الشخصي',
      'addToCart': 'أضف إلى عربة التسوق',
      'removeFromCart': 'إزالة من عربة التسوق',
      'quantity': 'الكمية',
      'total': 'المجموع',
      'checkout': 'إتمام الشراء',
      'proceedToCheckout': 'المتابعة إلى إتمام الشراء',
      'paymentSuccessful': 'تم الدفع بنجاح! تم تأكيد الطلب مقابل',
      'paymentFailed': 'فشل الدفع',
      'userNotAuthenticated': 'المستخدم غير مصادق عليه',
      'loading': 'جاري التحميل...',
      'error': 'خطأ',
      'success': 'نجح',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'edit': 'تعديل',
      'delete': 'حذف',
      'confirm': 'تأكيد',
      'clearCart': 'مسح عربة التسوق',
      'clearCartConfirmation': 'هل أنت متأكد من أنك تريد مسح عربة التسوق؟',
      'yes': 'نعم',
      'no': 'لا',
      'emptyCart': 'عربة التسوق فارغة',
      'cartSummary': 'ملخص عربة التسوق',
      'subtotal': 'المجموع الفرعي',
      'tax': 'الضريبة',
      'shipping': 'الشحن',
      'totalAmount': 'المبلغ الإجمالي',
      'itemCount': 'عدد العناصر',
      'items': 'العناصر',
      'processingCheckout': 'جاري معالجة إتمام الشراء...',
      'orderConfirmed': 'تم تأكيد الطلب',
      'orderFailed': 'فشل الطلب',
      'language': 'اللغة',
      'english': 'الإنجليزية',
      'arabic': 'العربية',
      'changeLanguage': 'تغيير اللغة',
      'selectLanguage': 'اختر اللغة',
      'currentLanguage': 'الغة الحالية',
      'languageChanged': 'تم تغيير اللغة',
      'languageChangeError': 'فشل في تغيير اللغة',
      'languageChangeSuccess': 'تم تغيير اللغة بنجاح',
      'languageChangeInfo': 'جاري تغيير اللغة...',
      'languageChangeConfirm': 'هل أنت متأكد من أنك تريد تغيير اللغة؟',
      'languageChangeCancel': 'إلغاء تغيير اللغة',
      'languageChangeSave': 'حفظ تغيير اللغة',
      'languageChangeReset': 'إعادة تعيين اللغة',
      'languageChangeDefault': 'اللغة الافتراضية',
      'languageChangeCustom': 'لغة مخصصة',
      'languageChangeSystem': 'لغة النظام',
      'languageChangeUser': 'لغة المستخدم',
      'languageChangeApp': 'لغة التطبيق',
      'languageChangeDevice': 'لغة الجهاز',
      'languageChangeLocale': 'لغة المنطقة',
      'languageChangeRegion': 'لغة المنطقة',
      'languageChangeCountry': 'لغة البلد',
      'languageChangeCurrency': 'لغة العملة',
      'languageChangeFormat': 'لغة التنسيق',
      'languageChangeDirection': 'لغة الاتجاه',
      'languageChangeRTL': 'من اليمين إلى اليسار',
      'languageChangeLTR': 'من اليسار إلى اليمين',
      'languageChangeAuto': 'تلقائي',
      'languageChangeManual': 'يدوي',
      'languageChangeOn': 'تشغيل',
      'languageChangeOff': 'إيقاف',
      'languageChangeEnabled': 'مفعل',
      'languageChangeDisabled': 'معطل',
      'languageChangeActive': 'نشط',
      'languageChangeInactive': 'غير نشط',
      'languageChangePrimary': 'أولي',
      'languageChangeSecondary': 'ثانوي',
      'languageChangeTertiary': 'ثالث',
      'languageChangeQuaternary': 'رابع',
      'languageChangeQuinary': 'خامس',
      'languageChangeSenary': 'سادس',
      'languageChangeSeptenary': 'سابع',
      'languageChangeOctonary': 'ثامن',
      'languageChangeNonary': 'تاسع',
      'languageChangeDenary': 'عاشر',
      'map': 'الخريطة',
    },
  };

  static String getString(BuildContext context, String key) {
    final locale = Localizations.localeOf(context);
    final languageCode = locale.languageCode;

    return _localizedStrings[languageCode]?[key] ??
        _localizedStrings['en']?[key] ??
        key;
  }

  static String getStringByLocale(String languageCode, String key) {
    return _localizedStrings[languageCode]?[key] ??
        _localizedStrings['en']?[key] ??
        key;
  }

  static bool isRTL(BuildContext context) {
    final locale = Localizations.localeOf(context);
    return locale.languageCode == 'ar';
  }

  static TextDirection getTextDirection(BuildContext context) {
    return isRTL(context) ? TextDirection.rtl : TextDirection.ltr;
  }
}
